services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go_pet_api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: pass
      DB_NAME: pet_db
      DB_SSLMODE: disable

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_pet_ap
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      API_URL: http://go_pet_api:8080
volumes:
  postgres_data:
