version: '3.8'
services:
  backend:
    container_name: go_pet_api
    build: 
      context: ./backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    container_name: angular_pet_app
    build: 
      context: ./frontend
    depends_on:
      - db
      - backend
    restart: unless-stopped
    ports:
    - "4200:4200"
    command: ng serve --host 0.0.0.0 --port 4200
volumes:
  postgres_data: